// import { IKeywordEligibility } from './../CreateKeyword/interfaces';
import {
  IData,
  IDetail,
  IGetKeywordData,
  IKeywordBonus,
  IkeywordPrime
} from "../../../redux/features/keyword/interface";

// import { IKeywordEligibility } from "../CreateKeyword/interfaces";

export const KeywordBonusInitial: IKeywordBonus = {
  _id: "",
  keyword: "",
  bonus_type: "",
  location: "",
  limit: 0,
  stock: 0,
  bucket: "",
  qty_denom: 0,
  payment: "",
  granular: "",
  bid: "",
  bonus_id: "",
  bonus_name: "",
  created_at: new Date(),
  updated_at: new Date(),
  deleted_at: new Date(),
  __v: 0,
  bonus_type_detail: [],
  location_detail: [],
  bucket_detail: [],
};
export const DetailInitial: IDetail = {
  name: "",
  start_period: new Date(),
  end_period: new Date(),
  point_type: [],
  point_value: "",
  for_new_redeemer: true,
  max_mode: "",
  max_redeem_counter: 0,
  max_redeem_per_msisdn: 0,
  channel_validation: [],
  merchandise_keyword: true,
  merchant: "",
  merchant_name: "",
  telkomsel_los_type: "",
  telkomsel_los_operator: "",
  telkomsel_los_value: 0,
  telkomsel_los_range_min: 0,
  telkomsel_los_range_max: 0,
  enable_coorporate: true,
  customer_tier: [],
  comment_approval: "",
  __v: 0,
};

export const KeywordItemInitial: IData = {
  _id: "",
  name: "",
  start_period: new Date(),
  end_period: new Date(),
  merchant: "",
  merchant_name: "",
  foreign_collection: "",
  foreign_id: "",
  keyword_approval: "",
  created_at: new Date(),
  updated_at: new Date(),
  deleted_at: new Date(),
  detail: DetailInitial,
  keyword_bonus: [KeywordBonusInitial],
  __v: 0,
};

export const GetKeywordDataInitial: IGetKeywordData = {
  channel_validation: [],
  comment_approval: "",
  created_at: "",
  customer_tier: [],
  deleted_at: null,
  enable_coorporate: true,
  end_period: "",
  for_new_redeemer: true,
  keyword_bonus: [],
  max_mode: "",
  max_redeem_counter: 0,
  max_redeem_per_msisdn: 0,
  merchandise_keyword: true,
  merchant: "",
  merchant_name: "",
  name: "",
  point_type: [],
  point_value: "",
  start_period: "",
  telkomsel_los_operator: "",
  telkomsel_los_range_max: 0,
  telkomsel_los_range_min: 0,
  telkomsel_los_type: "",
  telkomsel_los_value: 0,
  updated_at: "",
  __v: 0,
  _id: "",
};

export const IKeywordPrime : IkeywordPrime = {
  bonus: [],
  created_at: "",
  created_by: {},
  deleted_at: null,
  eligibility: {},
  keyword_approval: "",
  notification: [],
  updated_at: "",
  __v: 0,
  _id: ""
}
