image: node:16

pipelines:
  branches:
    staging:
      - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn
              - CI= yarn build
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
               SSH_USER: 'ec2-user'
               SERVER: '18.143.54.48'
               COMMAND: '/bin/bash pipeline-deploy/run-SLRevampFE.sh'