export const BONUS_TELKOMSEL_LINK_AJA_MAIN = "linkaja_main";
export const BONUS_TELKOMSEL_LINK_AJA_BONUS = "linkaja_bonus";
export const BONUS_TELKOMSEL_NGRS = "ngrs";
export const BONUS_TELKOMSEL_TELCO_PREPAID = "telco_prepaid";
export const BONUS_TELKOMSEL_TELCO_POSTPAID = "telco_postpaid";
export const BONUS_TELKOMSEL_LIST = [
	BONUS_TELKOMSEL_LINK_AJA_MAIN,
	BONUS_TELKOMSEL_LINK_AJA_BONUS,
	BONUS_TELKOMSEL_NGRS,
	BONUS_TELKOMSEL_TELCO_PREPAID,
	BONUS_TELKOMSEL_TELCO_POSTPAID
];
