// LOV GROUP NAME LIST
export const LOV_GROUP_NAME_LIST = [
    'CUSTOMER_TYPE',
    'LUCKY_DRAW_NOTIFICATION',
    'TELCO_POSTPAID_NOTIFICATION',
    'TELCO_PREPAID_NOTIFICATION',
    'KEYWORD_TYPE',
    'KEYWORD_APPROVAL_STATUS',
    'LOCATION_TYPE',
    'MECHANISM',
    'NOTIF_RECEIVER',
    'NOTIF_TYPE',
    'NOTIF_VIA',
    'POINT_TYPE',
    'PROGRAM_APPROVAL_STATUS',
    'PROGRAM_EXPERIENCE',
    'PROGRAM_NOTIFICATION_TEMPLATE'
];
