// VOUCHER COMBINATION
export const VOUCHER_COMBINATION_ALPHABET = "Alphabet";
export const VOUCHER_COMBINATION_NUMERIC = "Numeric";
export const VOUCHER_COMBINATIONS = [
	VOUCHER_COMBINATION_ALPHABET,
	VOUCHER_COMBINATION_NUMERIC
];

// VOUCHER TYPES
export const VOUCHER_TYPE_UPLOAD = "Upload";
export const VOUCHER_TYPE_GENERATE = "Generate";
export const VOUCHER_TYPES = [VOUCHER_TYPE_UPLOAD, VOUCHER_TYPE_GENERATE];
