// LOCAL STORAGE
const TOKEN = 'TOKEN'

// SET DATA
const SET_DATA_KEYWORD = 'SET_DATA_KEYWORD';


// GET DATA
const GET_DATA_KEYWORD = 'GET_DATA_KEYWORD';

export {
    TOKEN,
    SET_DATA_KEYWORD,
    GET_DATA_KEYWORD,
};
