import { ICreateKeyword } from "./interfaces";

// export const CreateKeywordGeneral: ICreateKeyword = {
//   keyword_type: "",
//   keyword_parent: "",
//   name: "",
//   start_period: new Date(),
//   end_period: new Date(),
//   point_type: "",
//   poin_value: "",
//   poin_redeemed: 0,
//   max_mode: "",
//   max_redeem_counter: 0,
//   merchandise_keyword: false,
//   enable_sms_masking: false,
//   sms_masking: "",
//   keyword_schedule_type: "",
//   keyword_schedule_shift: [
//     {
//       from: "",
//       to: "",
//     },
//   ],
//   program_bersubsidi: false,
//   total_anggaran: 0,
//   customer_value: 0,
//   multiwhitelist: false,
//   multiwhitelist_program: "",
//   channel_validation: false,
//   channel_validation_list: [],
//   program_experience: [],
//   merchant: "",
//   segmentation_customer_tier: [],
//   segmentation_customer_brand: [],
//   segmentation_customer_most_redeem: [],
//   segmentation_customer_prepaid_registration: false,
//   segmentation_customer_los_operator: "",
//   segmentation_customer_los: 0,
//   segmentation_customer_los_min: 0,
//   segmentation_customer_los_max: 0,
//   for_new_redeemer: false,
//   enable_corporate: false,
//   segmentation_customer_kyc_completeness: false,
//   segmentation_customer_arpu_operator: "",
//   segmentation_customer_arpu_min: 0,
//   segmentation_customer_arpu_max: 0,
//   segmentation_employee_numbers: false,

//   keyword_verification: "63027a5f0c3cd2fee9dffd58",
//   program_title_expose: "Program Name to be Exposed",
//   timezone: "General",
//   segmentation_customer_type: "Regular",
//   segmentation_customer_preferences_bcp: "TESTING",

//   keyword_bonus: [
//     {
//       bonus_type: "",
//       location: "",
//       bucket: "",
//       bonus_id: "",
//       bonus_name: "",
//       bid: "",
//       granular: "",
//       stock: 0,
//       qty_denom: 0,
//       limit: 0,
//       payment: "TRF",
//     },
//   ],
//   keyword_notification: [
//     {
//       via: "",
//       notif_type: "",
//       notification: "",
//       transaction_type: "",
//       notification_content: "",
//     },
//   ],
//   keyword_shift: [
//     {
//       from: "00:00",
//       to: "00:00",
//     },
//   ],
// };

export const CreateKeywordGeneral: ICreateKeyword = {
  name: "",
  start_period: new Date(),
  end_period: new Date(),
  keyword_type: "",
  point_type: "",
  keyword_verification: "",
  keyword_schedule_shift: [
    {
      from: new Date(),
      to: new Date(),
    },
  ],
  poin_value: "",
  poin_redeemed: 0,
  channel_validation: false,
  enable_corporate: false,
  channel_validation_list: [],
  program_title_expose: "",
  merchant: "",
  merchandise_keyword: false,
  keyword_schedule_type: "",
  program_bersubsidi: false,
  total_anggaran: 0,
  customer_value: 0,
  multiwhitelist: false,
  multiwhitelist_program: "",
  enable_sms_masking: false,
  sms_masking: "",
  timezone: "",
  for_new_redeemer: false,
  max_mode: "",
  max_redeem_counter: 0,
  program_experience: [],
  segmentation_customer_tier: [],
  segmentation_customer_los_operator: "",
  segmentation_customer_los: 0,
  segmentation_customer_los_max: 0,
  segmentation_customer_los_min: 0,
  segmentation_customer_type: "",
  segmentation_customer_most_redeem: [],
  segmentation_customer_brand: [],
  segmentation_customer_prepaid_registration: false,
  segmentation_customer_kyc_completeness: false,
  segmentation_customer_arpu_operator: "",
  segmentation_customer_arpu: 0,
  segmentation_customer_arpu_min: 0,
  segmentation_customer_arpu_max: 0,
  segmentation_customer_preferences_bcp: "",
  segmentation_employee_numbers: false,
  keyword_parent: "",
  keyword_bonus: [
    {
      bonus_type: "",
      location: "",
      limit: 0,
      stock: 0,
      bucket: "",
      qty_denom: 0,
      payment: "",
      granular: "",
      bid: "",
      bonus_id: "",
      bonus_name: "",
    },
  ],
  keyword_notification: [
    {
      notification: "",
      notification_content: "",
      notif_type: "",
      transaction_type: "",
      via: "",
    },
  ],
  keyword_shift: [
    {
      from: new Date(),
      to: new Date(),
    },
  ],
};

export interface IKeywordLocationTypeGeneral {
  location_type: string;
}

export const KeywordLocationTypeGeneral: IKeywordLocationTypeGeneral = {
  location_type: "",
};
