import { ICreateKeyword } from "./interfaces";

export const CreateKeywordGeneral: ICreateKeyword = {
  keyword_type: "",
  keyword_parent: "",
  name: "",
  start_period: new Date(),
  end_period: new Date(),
  point_type: [],
  poin_value: "",
  poin_redeemed: 0,
  max_mode: "",
  max_redeem_counter: 0,
  merchandise_keyword: false,
  enable_sms_masking: false,
  sms_masking: "",
  keyword_schedule_type: "",
  keyword_schedule_shift: [
    {
      from: "",
      to: "",
    },
  ],
  program_bersubsidi: false,
  total_anggaran: 0,
  customer_value: 0,
  multiwhitelist: false,
  multiwhitelist_program: "",
  channel_validation: false,
  channel_validation_list: [],
  program_experience: [],
  merchant: "",
  segmentation_customer_tier: [],
  segmentation_customer_brand: [],
  segmentation_customer_most_redeem: [],
  segmentation_customer_prepaid_registration: false,
  segmentation_customer_los_operator: "",
  segmentation_customer_los: 0,
  segmentation_customer_los_min: 0,
  segmentation_customer_los_max: 0,
  for_new_redeemer: false,
  enable_corporate: false,
  segmentation_customer_kyc_completeness: false,
  segmentation_customer_arpu_operator: "",
  segmentation_customer_arpu_min: 0,
  segmentation_customer_arpu_max: 0,
  segmentation_employee_numbers: false,
  keyword_bonus: [
    {
      bonus_type: "",
      location: "",
      bucket: "",
      bonus_id: "",
      bonus_name: "",
      bid: "",
      granular: "",
      stock: 0,
      qty_denom: 0,
      limit: 0,
      payment: "TRF",
    },
  ],
  keyword_notification: [
    {
      via: "",
      receiver: "",
      notif_type: "",
      notification: "",
      transaction_type: "",
      notification_content: "",
    },
  ],
};
